# Generated by Django 3.1.8 on 2021-08-21 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callrouting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='ETA',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='arrive_time',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='dispatch_time',
        ),
        migrations.CreateModel(
            name='ServiceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ETA', models.DateTimeField(blank=True, default=None, null=True)),
                ('dispatch_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('arrive_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('completion_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callrouting.servicerequest')),
            ],
        ),
    ]
