# Generated by Django 3.1.8 on 2021-08-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callrouting', '0002_auto_20210821_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='assigned_technician',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='manager',
        ),
    ]
