# Generated by Django 3.1.8 on 2021-08-22 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callrouting', '0004_auto_20210821_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractedcopier',
            name='service_history',
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_performed', models.CharField(default=None, max_length=150, null=True)),
                ('copier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='callrouting.contractedcopier')),
            ],
        ),
    ]
